#!/bin/bash

#DNS Reverso

echo " "
echo "######################################################"
echo "####### INICIO DE VARREDURA DNS REVERSO #############"
echo "#####################################################"

for ip in $(seq 1 254);
do
    host $3.$ip | grep -v NXDOMAIN
done

echo " "
echo "######################################################"
echo "####### FIM  DE VARREDURA DNS REVERSO #############"
echo "#####################################################"
