#!/bin/bash

#Transferencia de zona DNS

if [ "$1" == "" ] #testa o argumento
then
        echo "Siga o exemplo abaixo para passagem de parametros, passando o nome de domínio"
        echo " $0 batatinha.com.br"

else

        echo " "
        echo "######################################################"
        echo "####### TESTE DE TRANSFERENCIA DE ZONA DNSv###########"
        echo "#####################################################"
        for ns in $(host -t ns $1 | cut -d " " -f4);
        do
                host -l $1 $ns | grep "has address"
        done

        echo " "
        echo "######################################################"
        echo "############# FIM ###################################"
        echo "#####################################################"
fi

