#!/bin/bash

#Transferencia de zona DNS
echo " "
echo "######################################################"
echo "####### TESTE DE TRANSFERENCIA DE ZONA DNSv###########"
echo "#####################################################"
for ns in $(host -t ns $1 | cut -d " " -f4);
do
    	host -l $1 $ns | grep "has address"
done

echo " "
echo "######################################################"
echo "############# FIM ###################################"
echo "#####################################################"
