#!/bin/bash

if [ "$1" == "" ] #testa o argumento
then
        echo "Siga o exemplo abaixo para passagem de parametros, passando o nome de dominio"
        echo " $0 dominio wordlist"

else
   clear
        echo "######################################################"
        echo "####### INICIO VARREDURA DE ENTRADAS DNS #############"
        echo "######################################################"
        for rato in $(cat $2);
        do
        dominio=$rato"."$1
        host $dominio | grep "has address" | awk '{print $1, "- " $4'}

        done

        echo "######################################################"
        echo "######## FIM VARREDURA DE ENTRADAS DNS ###############"
        echo "######################################################"
fi
