#!/bin/bash

if [ "$1" == "" ] #testa o argumento
then
        echo "Siga o exemplo abaixo, passando o nome de domínio e a wordlist"
        echo " $0 dominio wordlist"

else
   clear
        echo "######################################################"
    echo "####### INICIO VARREDURA DE ENTRADAS DNS ###############"
    echo "#####################################################"
        for rato in $(cat $2);
        do
        dominio=$rato"."$1
        host $dominio | grep "has address" | awk '{print $1, "- " $4'}

        done

        echo "######################################################"
        echo "####### FIM VARREDURA DE ENTRADAS DNS ###############"
        echo "#####################################################"
fi
